apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: sample-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python
  template:
    metadata:
      labels:
        app: sample-python
    spec:
      containers:
      - name: sample-html
        image: abhishekf5/python-sample-app-demo:v1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: db-volume
          mountPath: /opt/secrets
      volumes:
      - name: db-volume
        secret:
          secretName: test-sample
